language: php

php:
  - 5.4
  - 5.5

env:
  - GUZZLE_VERSION=3.7.*
  - GUZZLE_VERSION=3.8.*

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar require guzzle/guzzle:${GUZZLE_VERSION} --no-update
  - php composer.phar install --dev

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/coveralls
  - vendor/bin/phpcs -v --report=summary --standard=PSR1,PSR2 src/ tests/
  - vendor/bin/phpmd src/,tests/ text codesize,unusedcode,design

